repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: node
        exclude: ^(.(?!.*\.ts$|.*\.tsx))*$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: ((.git)|(cz.yaml))
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.5
    hooks:
      - id: gitleaks
  - repo: https://github.com/crate-ci/typos
    rev: v1.3.3
    hooks:
      - id: typos
        exclude: ((.git)|(CHANGELOG.md))
